SRC_FOLDER = "src";
CDN_FOLDER = "cdn";
CONTENT_FOLDER = "content";
ENCRYPTED_FOLDER = "encrypted";
DECRYPTED_FOLDER = "decrypted";

ENCRYPTED_FOLDER_ENTIRE = `${__dirname}/${SRC_FOLDER}/${CDN_FOLDER}/${CONTENT_FOLDER}/${ENCRYPTED_FOLDER}`;
DECRYPTED_FOLDER_ENTIRE = `${__dirname}/${SRC_FOLDER}/${CDN_FOLDER}/${CONTENT_FOLDER}/${DECRYPTED_FOLDER}`;